### ISSUE TITLE
About CoCoSoDa Performance in Zero-shot Setting

### ISSUE THREAD

**Issue by Yubo8Zhang** [DeepSoftwareAnalytics/CoCoSoDa#2]
Hello,

I was very fortunate to read your paper, and the experimental results in Table V are exciting. The average score on CodeSearchNet dataset is 0.738, which outperforms UniXcoder and GraphCodeBERT by a substantial margin.

But when I try to reproduce the above result by the [pre-trained CoCoSoDa ](https://huggingface.co/DeepSoftwareAnalytics/CoCoSoDa)without any fine-tuning, the MRR on Python Dataset is 0.463. I don't know what went wrong. 

All the experiments are done on MacBook Pro 2022 with a M2 CPU.  A screenshot of the result is below：
![图片 1](https://user-images.githubusercontent.com/58507480/223903607-63f4c7a8-8b78-4c5a-afd0-3deba4791b3d.png)

--------------------------------------------------------------------------------
The bash script for the test is as follows：
```
lang=python
current_time=$(date "+%Y%m%d%H%M%S")
code_length=256
nl_length=128
model_type=multi-loss-cocosoda #"base", "cocosoda" ,"multi-loss-cocosoda"
moco_k=1024
moco_m=0.999
lr=2e-5
moco_t=0.07
max_steps=1000
aug_type_way=random_replace_type 
data_aug_type=random_mask
base_model=DeepSoftwareAnalytics/CoCoSoDa
CUDA_VISIBLE_DEVICES=

function fine-tune () {
output_dir=./saved_models/fine_tune/${lang}
mkdir -p `$output_dir`
 CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES} python run.py   --eval_frequency  100 \
    --moco_m ${moco_m} --moco_t ${moco_t}  \
    --model_type ${model_type} \
    --output_dir ${output_dir}  \
    --data_aug_type ${data_aug_type} \
    --moco_k ${moco_k} \
    --config_name=${base_model}  \
    --model_name_or_path=${base_model} \
    --tokenizer_name=${base_model} \
    --lang=$lang \
    --do_test \
    --test_data_file=dataset/$lang/test.jsonl \
    --codebase_file=dataset/$lang/codebase.jsonl \
    --code_length ${code_length} \
    --nl_length ${nl_length} \
    --eval_batch_size 64 \
    --learning_rate ${lr} \
    --seed 123456 2>&1| tee ${output_dir}/running.log
}
fine-tune
```

**Comment by s1530129650** [comment]
Thanks for your good question. This is caused by incorrect data processing. We have fixed it in https://github.com/DeepSoftwareAnalytics/CoCoSoDa/commit/ff8994098208e89e9e665919b4ce26bdcd55d62a.

In addition, we added the script to run the CoCoSoDa under the zero-shot setting [here](https://github.com/DeepSoftwareAnalytics/CoCoSoDa#zero-shot-running) and upload the corresponding running log on python [here](https://github.com/DeepSoftwareAnalytics/CoCoSoDa/blob/main/saved_models/zero-shot/python/running.log).

**Comment by s1530129650** [comment]
F
