### ISSUE TITLE
A question about do_multi_lang_continue_pre_train

### ISSUE THREAD

**Issue by yuanzhengming** [DeepSoftwareAnalytics/CoCoSoDa#3]
I would like to know the role of the if statement at line 190 in the model.py file. I think the presence of this line will prevent the model from learning the multimodal contrast later on
![捕获](https://user-images.githubusercontent.com/37107799/227151570-ba060bb1-77c8-4c9e-8399-3e2e802bf8c0.PNG)

**Comment by s1530129650** [comment]
You are right! Fixed it.
![image](https://user-images.githubusercontent.com/34572118/228161171-ae921921-b7fd-41d1-882f-835fa2614784.png)
https://github.com/DeepSoftwareAnalytics/CoCoSoDa/commit/2f2bf8e7994acef846ede7c1078a0b18bc4154d9
